Open annotation list
PDFTron/pdftron-flutter pull request #109
Opened 2021-07-14 20:57 UTC by dcupidon

Exposed an API that opens the exisitng annotation list upon the user's request

2021-07-14 22:15 UTC, sgong-pdftron requested changes

2021-07-14 22:15 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +    public static boolean[] listsVisible = {true, true, true};
for code readability, i would go with 3 boolean instead

2021-07-20 21:59 UTC, JamieDass approved these changes

2021-07-20 22:52 UTC, sgong-pdftron approved these changes

2021-07-21 22:20 UTC, merged