(Support) Goto Page Methods
PDFTron/pdftron-flutter pull request #121
Opened 2021-09-13 18:20 UTC by dcupidon

Exposed APIs for the following methods:
* gotoPreviousPage()
* gotoNextPage()
* gotoFirstPage()
* gotoLastPage()

2021-09-13 18:26 UTC, sgong-pdftron approved these changes
bump ver

2021-09-15 21:18 UTC, JamesTron requested changes

2021-09-15 21:18 UTC, JamesTron commented on API.md
> +Go to the previous page of the document. If on first page, it would stay on first page.
```suggestion
Go to the previous page of the document. If on first page, it will stay on first page.
```

2021-09-15 21:18 UTC, JamesTron commented on API.md
> +Go to the next page of the document. If on last page, it would stay on last page.
```suggestion
Go to the next page of the document. If on last page, it will stay on last page.
```

2021-09-15 21:19 UTC, JamesTron approved these changes

2021-09-15 21:34 UTC, merged