(Support) Get Current Page
PDFTron/pdftron-flutter pull request #132
Opened 2021-09-27 15:48 UTC by dcupidon

Exposed API to retrieve the current page being shown.

2021-09-27 15:50 UTC, sgong-pdftron requested changes
missing ver

2021-09-27 15:52 UTC, dcupidon commented
> missing ver

Version number has been bumped

2021-09-27 16:04 UTC, sgong-pdftron approved these changes

2021-09-30 02:47 UTC, JamesTron approved these changes

2021-09-30 02:50 UTC, merged