Miscellaneous Apis
PDFTron/pdftron-flutter pull request #161
Opened 2021-12-02 23:37 UTC by dcupidon

Added `autoResizeFreeTextEnabled` and `restrictDownloadUsage`.

2021-12-10 19:42 UTC, sgong-pdftron approved these changes

2021-12-15 20:52 UTC, JamesTron requested changes

2021-12-15 20:52 UTC, JamesTron commented on ios/Classes/PdftronFlutterPlugin.m
> +                lse if ([key isEqualToString:PTUserIdKey])
```suggestion
                else if ([key isEqualToString:PTUserIdKey])
```
Please double-check this all compiles.

2021-12-16 17:23 UTC, JamesTron approved these changes

2021-12-16 17:40 UTC, merged