Group Annotations API
PDFTron/pdftron-flutter pull request #185
Opened 2022-01-17 23:12 UTC by JamieDass

2022-01-20 16:50 UTC, sgong-pdftron requested changes

2022-01-20 16:50 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +                AnnotUtils.createAnnotationGroup(pdfViewCtrl, primaryAnnotation, subAnnotations);
is subAnnotations here all annot in group? if you read android API the third param is all in group @eamon-mallon

2022-01-20 23:07 UTC, sgong-pdftron approved these changes

2022-01-21 00:43 UTC, dluco approved these changes

2022-01-25 21:40 UTC, dluco approved these changes

2022-01-25 23:09 UTC, sgong-pdftron approved these changes

2022-01-25 23:44 UTC, merged