[Support] Quick Bookmark Creation Config Option
PDFTron/pdftron-flutter pull request #202
Opened 2022-03-09 23:29 UTC by kmathew-pdftron

2022-03-10 16:40 UTC, sgong-pdftron requested changes

2022-03-10 16:40 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/ViewerImpl.java
> +        public void onBookmarkModified(@NonNull List<UserBookmarkItem> bookmarkItems) {
move everything in `onBookmarkModified()` to here as `onBookmarkModified()` is getting deprecated

2022-03-10 17:40 UTC, sgong-pdftron approved these changes
missing api docs and version, otherwise android code looks fine

2022-03-23 17:34 UTC, JamieDass approved these changes

2022-03-23 18:09 UTC, merged