Other zoom methods
PDFTron/pdftron-flutter pull request #212
Opened 2022-03-25 18:43 UTC by kmathew-pdftron

other zoom methods

2022-04-04 16:26 UTC, JamieDass approved these changes

2022-04-20 18:49 UTC, sgong-pdftron requested changes

2022-04-20 18:49 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +                zoomWithCenter(call, result, component);
break

2022-04-20 18:49 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +                try{
format

2022-04-20 19:47 UTC, sgong-pdftron requested changes

2022-04-20 19:47 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +    private static void zoomWithCenter(MethodCall call, MethodChannel.Result result, ViewerComponent component){
this file is still not formatted

2022-04-20 19:47 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +    private static void zoomToRect(MethodCall call, MethodChannel.Result result, ViewerComponent component) throws PDFNetException{
since there is a catch in this function, not sure what is throwing `PDFNetException`?

2022-04-20 22:43 UTC, sgong-pdftron requested changes

2022-04-20 22:43 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +        result.success(null);
this should be moved inside the try block otherwise you'd run error and success both because no return after error

2022-04-20 22:50 UTC, sgong-pdftron approved these changes

2022-04-20 23:04 UTC, merged