Scrollpos methods
PDFTron/pdftron-flutter pull request #217
Opened 2022-04-12 17:57 UTC by kmathew-pdftron

2022-06-09 16:26 UTC, sgong-pdftron requested changes

2022-06-09 16:26 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +                    getScrollPos(result,component);
format

2022-06-09 16:26 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +        jsonObject.put(REFLOW_ORIENTATION_HORIZONTAL,  pdfViewCtrl.getHScrollPos());
format

2022-06-09 16:26 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +        jsonObject.put(REFLOW_ORIENTATION_VERTICAL, pdfViewCtrl.getVScrollPos());
this key looks strange to me, as there is nothing to do with reflow here

2022-06-21 21:27 UTC, sgong-pdftron requested changes

2022-06-21 21:27 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +        pdfViewCtrl.setHScrollPos((int) (horizontalScrollPosition + 0.5));
unsure why the 0.5 is needed, original value is int, the method expects int as well

2022-06-21 21:27 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +        pdfViewCtrl.setVScrollPos((int) (verticalScrollPosition + 0.5));
same here, why need to add 0.5

2022-06-28 23:24 UTC, sgong-pdftron commented
too many conflicts

2022-07-04 21:59 UTC, sgong-pdftron approved these changes

2022-07-20 23:00 UTC, dluco approved these changes

2022-08-26 22:52 UTC, merged