On scroll changed event listener
PDFTron/pdftron-flutter pull request #219
Opened 2022-04-14 18:33 UTC by kmathew-pdftron

2022-04-14 19:13 UTC, sgong-pdftron requested changes
please refer to react native on implementation, it's entirely off track here

2022-04-14 19:18 UTC, JamieDass approved these changes
I think iOS looks ok

2022-06-06 23:36 UTC, terryyoon-pdftron commented
@sgong-pdftron

2022-06-07 14:28 UTC, sgong-pdftron requested changes

2022-06-07 14:28 UTC, sgong-pdftron commented on android/build.gradle
> +            url "https://pdftron-maven.s3.amazonaws.com/snapshot"
looks like bad merge here should revert

2022-06-07 16:17 UTC, sgong-pdftron approved these changes

2022-06-07 16:18 UTC, sgong-pdftron approved these changes

2022-06-08 20:48 UTC, merged