Implement commit-tool, get-page-count and handle-back-button
PDFTron/pdftron-flutter pull request #30
Opened 2020-10-05 16:46 UTC by Maxwell-Yang-PDFTron

2020-10-14 17:04 UTC, sgong-pdftron requested changes

2020-10-14 17:04 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/PluginUtils.java
> +                handleBackButton(result, component);
missing break

2020-10-14 17:04 UTC, sgong-pdftron commented on README.md
> +PdftronFlutter.commitTool().then((value) {
for all three

2020-10-14 23:51 UTC, JamesTron requested changes
Just some documentation suggestions.

2020-10-14 23:51 UTC, JamesTron commented on README.md
> +Commits the current tool.
Maybe instead:
Commits the annotation being created by the tool to the PDF.

2020-10-14 23:51 UTC, JamesTron commented on README.md
> +To get the current page count of the document.
Instead:
Returns the total number of pages in the currently displayed document.

2020-10-15 16:09 UTC, JamesTron approved these changes

2020-10-15 16:13 UTC, sgong-pdftron approved these changes

2020-10-15 16:13 UTC, merged