[Android] Update to 10.8.0
PDFTron/pdftron-flutter pull request #321
Opened 2024-03-18 19:23 UTC by sgong-pdftron

2024-03-18 22:57 UTC, ama-pdftron requested changes

2024-03-18 22:57 UTC, ama-pdftron commented on CHANGELOG.md
> +- Update Android to v10.7.0
Should be 10.8.0

2024-03-18 22:57 UTC, ama-pdftron commented on CHANGELOG.md
> +- Update Android to v10.7.0
And March 20

2024-03-19 18:36 UTC, brandenfung2 approved these changes

2024-03-19 19:26 UTC, merged