Add annotations (freeText)
PDFTron/pdftron-flutter pull request #72
Opened 2021-03-02 17:29 UTC by Maxwell-Yang-PDFTron

2021-04-01 23:46 UTC, JamesTron requested changes

2021-04-01 23:46 UTC, JamesTron commented on ios/Classes/PdftronFlutterPlugin.m
> +//        [self.tabbedDocumentViewController.navigationController dismissViewControllerAnimated:YES completion:nil];
Is this on purpose?

2021-04-01 23:46 UTC, JamesTron commented on ios/Classes/PdftronFlutterPlugin.m
> +- (void)addAnnotations:(NSString *)annotations resultToken:(FlutterResult)flutterResult
Since we only currently support FreeText, can we have an error message that states exactly why other types aren't possible (now)?

2021-04-05 16:03 UTC, sgong-pdftron requested changes

2021-04-05 16:03 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +                annot.getPage().annotPushBack(annot);
never use annot.getpage

2022-08-26 23:54 UTC, sgong-pdftron commented
Closing as we should look for better way to implement this functionality

2022-08-26 23:54 UTC, closed without merging