Add deleteAllAnnotations method to the sdk
PDFTron/pdftron-flutter pull request #89
Opened 2021-05-11 22:46 UTC by sbazzaz

Add deleteAllAnnotations method to the flutter sdk

## Support Ticket
https://support.pdftron.com/a/tickets/21782

## Issues Closed or Referenced

## Description of Changes

## Screenshots

2021-05-11 22:50 UTC, sgong-pdftron requested changes

2021-05-11 22:50 UTC, sgong-pdftron commented on API.md
> +Deletes all annotations in the current document.
add "Exclude links and widget"

2021-05-11 22:50 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +import com.pdftron.pdf.utils.AnalyticsHandlerAdapter;
remove

2021-05-11 22:50 UTC, sgong-pdftron commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +            AnalyticsHandlerAdapter.getInstance().sendException(e);
just print out e.printStackTrace();

2021-05-11 23:08 UTC, sbazzaz commented on API.md
> +Deletes all annotations in the current document.
Done.

2021-05-11 23:08 UTC, sbazzaz commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +import com.pdftron.pdf.utils.AnalyticsHandlerAdapter;
Done.

2021-05-11 23:08 UTC, sbazzaz commented on android/src/main/java/com/pdftron/pdftronflutter/helpers/PluginUtils.java
> +            AnalyticsHandlerAdapter.getInstance().sendException(e);
Done.

2021-05-11 23:29 UTC, sgong-pdftron approved these changes

2021-05-12 19:09 UTC, JamesTron commented on ios/Classes/PdftronFlutterPlugin.m
> +    [documentController.toolManager changeTool:[PTPanTool class]];
We should call these even when there is an error.

2021-05-12 19:13 UTC, merged