Publishing to pub.dev
PDFTron/pdftron-flutter pull request #99
Opened 2021-06-11 17:24 UTC by dcupidon

We have completed the changes needed for the package to be published on pub.dev.

2021-06-23 17:01 UTC, sgong-pdftron approved these changes

2021-06-23 20:56 UTC, JamesTron approved these changes
See comments. Would be nice to clarify first one, second one can be added to a backlog somewhere.

2021-06-23 20:56 UTC, JamesTron commented on doc/api/API.md
>  We suggest that you stick with either version for the APIs that are callable in both versions, to avoid unnecessary problems.
I don't quite understand this sentence. Do you mean choose either widget or plugin, but not both?

2021-06-23 20:56 UTC, JamesTron commented on lib/constants.dart
>    static const annotationSmartPen = 'AnnotationSmartPen';
This exists in iOS native too.

2021-06-25 21:46 UTC, JamesTron commented on doc/api/API.md
> +We suggest that you pick either widget or plugin and stick with that choice for all APIs, excluding APIs that are only available in one version.
```suggestion
You must choose either the widget or plugin, and use it for all APIs. Mixing widget and plugin APIs will not function correctly.
```

2021-06-25 21:46 UTC, JamesTron approved these changes

2022-02-22 23:03 UTC, sgong-pdftron requested changes

2022-02-22 23:03 UTC, sgong-pdftron commented on CHANGELOG.md
> +- Toggle widget and plugin
this is done for internal sample so not actually related to customer, should either remove, or mention it's only for the internal sample

2022-02-22 23:03 UTC, sgong-pdftron commented on README.md
> +Dart now supports [sound null safety](https://dart.dev/null-safety), which is available starting from Dart 2.12.0 and Flutter 2.0.0.  Upgrading may cause breaking changes, so if you are not ready to
this needs to be updated because master is also null safety

2022-02-22 23:03 UTC, sgong-pdftron commented on README.md
> +- [GitHub](https://github.com/PDFTron/pdftron-flutter/tree/publish-prep) (You are currently on this branch)
missing update

2022-02-23 17:47 UTC, sgong-pdftron requested changes

2022-02-23 17:47 UTC, sgong-pdftron commented on README.md
> +Dart now supports [sound null safety](https://dart.dev/null-safety), which is available starting from Dart 2.12.0 and Flutter 2.0.0.
should link to some official migration guide in case client is not ready for it

2022-02-23 18:50 UTC, sgong-pdftron approved these changes

2022-02-23 19:09 UTC, merged